version: '3.7'

networks:
  fonoster:

services:
  rox:
    build:
      context: .  
    image: fonoster/rox:latest
    command: ['rox']
    restart: ${RESTART_POLICY}
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - INTENTS_ENGINE
      - INTENTS_ENGINE_AGENT
      - INTENTS_ENGINE_LOCATION
      - ASR_ENGINE
      - TTS_ENGINE
      - TTS_VOICE
      - INITIAL_DTMF
      - WELCOME_INTENT_TRIGGER
      - ACTIVATION_INTENT
      - INTERACTION_TIMEOUT
      - EVENTS_ENABLED
      - ACTIVATION_TIMEOUT
      - LANGUAGE_CODE
      - OTL_EXPORTER_ZIPKIN_URL
      - OTL_EXPORTER_JAEGER_URL
      - OTL_EXPORTER_PROMETHEUS_PORT
      - OTL_EXPORTER_GCP_ENABLED
    volumes:
      - ${CONFIG}/google.json:/home/fonoster/.fonoster/google.json
    networks:
      fonoster:
        aliases: 
          - ${ROX_HOST}